import { Tour } from "@/types";

export const MOCK_TOURS: Tour[] = [
  {
    id: "1",
    title: "Porto Medieval Walking Tour",
    slug: "porto-medieval-walking-tour",
    description:
      "Journey back to the Middle Ages as we walk through Porto's medieval quarter. Discover the ancient walls, the Romanesque Cathedral, and hidden streets that tell the story of a city forged by commerce and conquest. Led by archaeologist Fábio Soares, this tour brings centuries of history to life with expert storytelling and exclusive access to lesser-known sites.",
    short_description:
      "Explore Porto's medieval heritage — from the Romanesque Cathedral to the ancient Fernandina Wall.",
    duration_minutes: 150,
    price_eur: 35,
    max_participants: 12,
    category: "historical",
    zone: "porto",
    image_url: "https://www.civitatis.com/f/portugal/oporto/galeria/panoramica-oporto-medieval.jpg",
    gallery_urls: [],
    highlights: [
      "Sé Cathedral – Porto's Romanesque fortress-church",
      "Fernandina Wall – the medieval defensive perimeter",
      "Rua das Flores – historic merchant street",
      "Hidden medieval courtyards and alleyways",
      "Exclusive archaeological insights from Fábio Soares",
    ],
    meeting_point: "Sé Cathedral Main Entrance",
    meeting_point_coords: { lat: 41.1427, lng: -8.6117 },
    is_active: true,
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Port Wine Heritage Trail",
    slug: "port-wine-heritage-trail",
    description:
      "Cross the iconic Dom Luís I Bridge into Vila Nova de Gaia and uncover the centuries-old story of Port wine. Visit historic cellars, learn about the barcos rabelos that transported wine barrels down the Douro, and taste curated selections — all framed by the rich history that made Porto's wine world-famous.",
    short_description:
      "From Ribeira to Gaia — the history, the cellars, and the taste of Port wine.",
    duration_minutes: 180,
    price_eur: 45,
    max_participants: 10,
    category: "wine",
    zone: "both",
    image_url: "https://www.travelawaits.com/wp-content/uploads/2021/04/eefcd88c5df6268869b151a896aa8eefcd8-scaled.jpg?w=800",
    gallery_urls: [],
    highlights: [
      "Dom Luís I Bridge crossing with panoramic views",
      "Historic Port wine cellars in Gaia",
      "The story of barcos rabelos and the Douro trade",
      "Guided wine tasting of curated Port selections",
      "Cais da Ribeira UNESCO World Heritage site",
    ],
    meeting_point: "Praça da Ribeira Fountain",
    meeting_point_coords: { lat: 41.1405, lng: -8.6132 },
    is_active: true,
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "3",
    title: "Azulejo Art & Stories",
    slug: "azulejo-art-and-stories",
    description:
      "Portugal's iconic blue tiles are more than decoration — they are narrative art. This tour takes you through Porto's most stunning azulejo collections, from the grand São Bento Railway Station to the ornate Igreja do Carmo, revealing the history, symbolism, and craftsmanship behind each panel.",
    short_description:
      "Discover the history and symbolism behind Porto's world-famous blue tile art.",
    duration_minutes: 120,
    price_eur: 30,
    max_participants: 14,
    category: "azulejo",
    zone: "porto",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d3/%C3%93bidos_-_Varanda_%285414515924%29.jpg",
    gallery_urls: [],
    highlights: [
      "São Bento Station — 20,000 hand-painted tiles",
      "Igreja do Carmo — baroque azulejo masterpiece",
      "Chapel of Souls — fully tiled façade",
      "Evolution of azulejo art from Moorish to modern",
      "Hidden tile gems off the tourist trail",
    ],
    meeting_point: "São Bento Railway Station Main Hall",
    meeting_point_coords: { lat: 41.1456, lng: -8.6102 },
    is_active: true,
    created_at: "2026-01-20T10:00:00Z",
  },
  {
    id: "4",
    title: "Legends & Mysteries Night Tour",
    slug: "legends-and-mysteries-night-tour",
    description:
      "As the sun sets over the Douro, a different Porto emerges. This evening tour takes you through dimly lit alleys and ancient squares, uncovering legends of hidden treasures, ghostly monks, and the darker chapters of Porto's past. A unique experience blending history with storytelling under the city lights.",
    short_description:
      "Explore Porto after dark — legends, ghost stories, and the city's hidden history.",
    duration_minutes: 120,
    price_eur: 30,
    max_participants: 15,
    category: "nocturnal",
    zone: "porto",
    image_url: "/images/tours/night-porto.jpg",
    gallery_urls: [],
    highlights: [
      "Porto's haunted spots and legendary tales",
      "The mystery of the Clérigos Tower at night",
      "Dark chapters of the Inquisition in Porto",
      "Atmospheric walk through candlelit streets",
      "Sunset views from Jardim do Morro",
    ],
    meeting_point: "Clérigos Tower Base",
    meeting_point_coords: { lat: 41.1458, lng: -8.6146 },
    is_active: true,
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "5",
    title: "Taste of Porto Food Walk",
    slug: "taste-of-porto-food-walk",
    description:
      "Porto's culinary traditions are deeply rooted in history. From the bustling Bolhão Market to hidden tascas, this tour traces the origins of Porto's most iconic dishes — the francesinha, tripas à moda do Porto, and pastéis de nata — while exploring the neighborhoods that shaped them.",
    short_description:
      "A culinary journey through Porto's markets, tascas, and the stories behind iconic dishes.",
    duration_minutes: 180,
    price_eur: 50,
    max_participants: 10,
    category: "gastronomic",
    zone: "porto",
    image_url: "/images/tours/food-porto.jpg",
    gallery_urls: [],
    highlights: [
      "Bolhão Market — Porto's historic food hub",
      "The origin story of the francesinha sandwich",
      "Traditional tascas with local tastings",
      "Pastéis de nata from a century-old bakery",
      "Why Porto locals are called 'tripeiros'",
    ],
    meeting_point: "Bolhão Market Main Entrance",
    meeting_point_coords: { lat: 41.1496, lng: -8.6059 },
    is_active: true,
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "6",
    title: "Literary Porto: From Camilo to Rowling",
    slug: "literary-porto-from-camilo-to-rowling",
    description:
      "Porto has inspired writers for centuries. Walk in the footsteps of Camilo Castelo Branco, discover where JK Rowling found inspiration for Harry Potter, and visit the Lello Bookstore — one of the world's most beautiful. This tour weaves literature, architecture, and history into a single, unforgettable narrative.",
    short_description:
      "Walk in the footsteps of writers — from Camilo Castelo Branco to JK Rowling's Porto.",
    duration_minutes: 120,
    price_eur: 30,
    max_participants: 12,
    category: "literary",
    zone: "porto",
    image_url: "/images/tours/literary-porto.jpg",
    gallery_urls: [],
    highlights: [
      "Livraria Lello — one of the world's most beautiful bookshops",
      "JK Rowling's Porto: the cafés and streets that inspired Harry Potter",
      "University of Porto's literary legacy",
      "Camilo Castelo Branco's romantic Porto",
      "Hidden literary cafés and bookshops",
    ],
    meeting_point: "Praça dos Leões (Martires da Pátria)",
    meeting_point_coords: { lat: 41.1472, lng: -8.6159 },
    is_active: true,
    created_at: "2026-02-15T10:00:00Z",
  },
];

export const MOCK_REVIEWS = [
  {
    id: "r1",
    tour_id: "1",
    rating: 5,
    comment:
      "Fábio is an incredible guide! His knowledge of Porto's medieval history is unmatched. We learned things you'd never find in a guidebook. Absolutely worth it!",
    user: { full_name: "Sarah M.", country: "United States" },
    created_at: "2026-03-10T14:00:00Z",
  },
  {
    id: "r2",
    tour_id: "2",
    rating: 5,
    comment:
      "The wine tasting was wonderful, but what made it special was the historical context. I finally understand why Port wine is so tied to this city. Highly recommend!",
    user: { full_name: "James T.", country: "United Kingdom" },
    created_at: "2026-03-15T16:00:00Z",
  },
  {
    id: "r3",
    tour_id: "3",
    rating: 5,
    comment:
      "I had no idea tiles could tell such stories! São Bento station will never look the same to me. Fábio's expertise as an archaeologist really shines through.",
    user: { full_name: "Emily R.", country: "Canada" },
    created_at: "2026-03-20T11:00:00Z",
  },
  {
    id: "r4",
    tour_id: "4",
    rating: 4,
    comment:
      "Such a unique experience. The night atmosphere combined with the legends made it feel magical. My only wish: it could have been even longer!",
    user: { full_name: "Michael B.", country: "Australia" },
    created_at: "2026-03-25T20:00:00Z",
  },
  {
    id: "r5",
    tour_id: "5",
    rating: 5,
    comment:
      "Best food tour we've ever done. Fábio doesn't just show you where to eat — he explains the history behind every dish. The francesinha backstory was fascinating.",
    user: { full_name: "Lisa & Mark K.", country: "United States" },
    created_at: "2026-04-01T13:00:00Z",
  },
];
